Repository OpenTTD/OpenTTD, pull requests merged in 2019-07, with the labels that each got.

#7634 Fix #7633: Allow zero-cost track conversion to succeed
  src/rail_cmd.cpp
  src/road_cmd.cpp
Labels: backport requested

#7480 Fix #6666: brackets in arabic strings
  src/gfx_layout.cpp
  src/lang/arabic_egypt.txt
Labels: backport requested, stale

#7560 Make GSGoal.QuestionClient work correctly at least for clients with ID < 2**16
  src/goal.cpp
  src/script/api/script_goal.cpp
  src/script/api/script_goal.hpp
Labels: backported

#7669 Fix #7655: Decrease buttons in cheat window do not work properly
  src/cheat_gui.cpp
Labels: backport requested
