Repository OpenTTD/OpenTTD, pull requests merged in 2019-03, with the labels that each got.

#7309 Fix #7307: Add WaterClass to MP_TREES
  docs/landscape.html
  docs/landscape_grid.html
  src/tree_map.h
  src/water_map.h
Labels: NewGRF

#7147 Change: Synchronize randomness in vehicle introduction…
  src/engine.cpp
Labels: needs triage

#7288 Fix 23960d0f2c: Company livery window shows incorrect groups when opened from group window in multiplayer.
  src/company_gui.cpp
Labels: bug

#6965 Add: Option for population-linear town cargo generation
  src/lang/english.txt
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings.ini
  src/town_cmd.cpp
  src/town_type.h
Labels: needs testing, savegame upgrade

#7335 Fix #7334: Ship lost after crossing bridge due to path cache not being consumed while on final bridge end.
  src/ship_cmd.cpp
Labels: backport, needs review, regression

#7336 Add: AI API for vehicle group colours
  src/script/api/ai/ai_group.hpp.sq
  src/script/api/ai_changelog.hpp
  src/script/api/script_group.cpp
  src/script/api/script_group.hpp
Labels: backport, needs review

#7234 Feature: Game setting to define how industries with neutral stations accept and supply cargo from/to surrounding stations.
  src/economy.cpp
  src/industry.h
  src/industry_cmd.cpp
  src/lang/english.txt
  src/saveload/afterload.cpp
  src/saveload/industry_sl.cpp
  src/saveload/saveload.h
  src/settings_gui.cpp
  src/settings_type.h
  src/station.cpp
  src/station_base.h
  src/station_cmd.cpp
  src/station_func.h
  src/table/settings.ini
Labels: needs review, savegame upgrade

#7345 Fix 13962a847, 00d28a500: forgotten squirrel_export run
  src/script/api/game/game_window.hpp.sq
Labels: backport

#7261 Add: Road vehicle path cache.
  src/pathfinder/pathfinder_type.h
  src/pathfinder/yapf/yapf.h
  src/pathfinder/yapf/yapf_node.hpp
  src/pathfinder/yapf/yapf_road.cpp
  src/pathfinder/yapf/yapf_ship.cpp
  src/roadveh.h
  src/roadveh_cmd.cpp
  src/saveload/saveload.h
  src/saveload/vehicle_sl.cpp
Labels: needs review, savegame upgrade

#7231 Add: Add flag and railtype sprite type to draw pre-combined ground sprites.
  src/rail.h
  src/rail_cmd.cpp
Labels: NewGRF, needs testing

#7356 Fix: [AzurePipelines] run commit checker only for PRs and pass it the…
  azure-pipelines/templates/ci-git-rebase.yml
  azure-pipelines/templates/linux-build.yml
Labels: to backport

#7367 Change: Include _current_company in crashlog AI config line
  src/crashlog.cpp
Labels: backport requested

#7392 Fix #7391, 9b99b95: Don't invalidate go to depot orders of non-aircra…
  src/order_backup.cpp
  src/order_cmd.cpp
Labels: backport requested

#7385 Fix: NewGRF feature cleanup.
  src/newgrf.cpp
Labels: backport requested

#7402 Fix: Filtered file list did not scroll properly.
  src/fios_gui.cpp
Labels: backport requested

#7431 Fix aa7ca7fe6: Linkgraph node index order must be maintained due to other references.
  src/linkgraph/linkgraph.cpp
Labels: regression
