Repository OpenTTD/OpenTTD, pull requests merged in 2020-06, with the labels that each got.

#8181 Fix #8066: Try another fallback colourspace if first one fails
  src/video/cocoa/wnd_quartz.mm
Labels: Mac OS, backport requested

#8091 Add: [Script] Native priority queue; useful e.g. for pathfinders.
  projects/openttd_vs140.vcxproj
  projects/openttd_vs140.vcxproj.filters
  projects/openttd_vs141.vcxproj
  projects/openttd_vs141.vcxproj.filters
  projects/openttd_vs142.vcxproj
  projects/openttd_vs142.vcxproj.filters
  source.list
  src/ai/ai_instance.cpp
  src/game/game_instance.cpp
  src/script/api/ai/ai_priorityqueue.hpp.sq
  src/script/api/ai_changelog.hpp
  src/script/api/game/game_priorityqueue.hpp.sq
  src/script/api/game_changelog.hpp
  src/script/api/script_priorityqueue.cpp
  src/script/api/script_priorityqueue.hpp
  src/script/api/template/template_priorityqueue.hpp.sq
  src/script/script_instance.cpp
  src/script/script_instance.hpp
Labels: AI/Game script (squirrel)

#8079 Add: [NewGRF] Industry behaviour flag to override second cargo produc…
  src/industry_cmd.cpp
  src/industrytype.h
Labels: NewGRF
