Repository OpenTTD/OpenTTD, pull requests merged in 2020-12, with the labels that each got.

#8379 Codechange: use \u to indicate unicode chars in most parts of the code
  src/currency.cpp
  src/misc_gui.cpp
  src/string_type.h
  src/table/townname.h
  src/textfile_gui.cpp
  src/townname.cpp
Labels: candidate: yes, size: small

#8282 Add: new economy "frozen" that stops production changes and industry closures
  src/economy_type.h
  src/industry_cmd.cpp
  src/industry_gui.cpp
  src/industrytype.h
  src/lang/english.txt
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings.ini
Labels: candidate: yes, size: small

#8278 Feature: tiles/day velocity unit
  src/lang/english.txt
  src/strings.cpp
  src/table/gameopt_settings.ini
  src/table/settings.ini
Labels: candidate: yes, size: small

#8352 Change: set the default setting for autorenew to on for new games
  regression/regression/main.nut
  regression/regression/result.txt
  src/table/company_settings.ini
Labels: candidate: yes, size: trivial

#7883 Fix: for original terrain generator, keep a single gap of water at the borders
  src/landscape.cpp
Labels: candidate: yes, size: small

#8337 Fix: Remove unnessary reference to suppress warning
  src/network/network_content.cpp
Labels: OS: MacOS, candidate: yes, needs review, size: trivial

#8382 Fix: [NewGRF] Action 7/9 conditions 0x0B to 0x12 failed, if 'param' was 0x85 or 0x88.
  src/newgrf.cpp
Labels: candidate: yes, needs review: NewGRF, size: trivial

#8385 Fix #8313: use correct capitalization for TTO / DOS base-music
  media/baseset/orig_dos.obm
  media/baseset/orig_tto.obm
Labels: candidate: yes, size: trivial

#8387 Change: send network error to the server before making an emergency save
  src/network/network_client.cpp
Labels: candidate: yes, size: trivial

#8386 Change: extend the allowed range for max loan setting
  regression/regression/result.txt
  src/company_cmd.cpp
  src/economy.cpp
  src/economy_type.h
  src/settings_gui.cpp
  src/table/settings.ini
Labels: candidate: yes, preview, size: trivial

#8409 Codechange: some comments for the win32 video driver
  src/video/win32_v.cpp
Labels: candidate: yes, size: trivial

#8400 Fix c02ef3e4: [NewGRF] Variable 0x44 is always HZB_TOWN_EDGE for roadstops
  src/newgrf_roadtype.cpp
Labels: candidate: needs considering, needs review: NewGRF, size: trivial

#7912 Feature: Disallow industry production changes from GS
  src/command.cpp
  src/command_type.h
  src/industry.h
  src/industry_cmd.cpp
  src/newgrf_industries.cpp
  src/saveload/industry_sl.cpp
  src/saveload/saveload.h
  src/script/api/game_changelog.hpp
  src/script/api/script_cargo.hpp
  src/script/api/script_industry.cpp
  src/script/api/script_industry.hpp
Labels: candidate: yes, component: AI/Game script (squirrel), savegame upgrade, size: large

#8115 GS methods to let company have exclusive access to the industry
  src/economy.cpp
  src/economy_func.h
  src/industry.h
  src/industry_cmd.cpp
  src/saveload/afterload.cpp
  src/saveload/industry_sl.cpp
  src/saveload/saveload.h
  src/script/api/game_changelog.hpp
  src/script/api/script_industry.cpp
  src/script/api/script_industry.hpp
  src/station_cmd.cpp
Labels: candidate: yes, component: AI/Game script (squirrel), size: large

#8416 Change: [Linkgraph] Allow job threads to be aborted early when clearing schedule
  src/linkgraph/linkgraphjob.cpp
  src/linkgraph/linkgraphjob.h
  src/linkgraph/linkgraphschedule.cpp
  src/linkgraph/mcf.cpp
Labels: candidate: yes, size: small

#8413 Fix: Don't lower tree density if spreading is not enabled
  src/tree_cmd.cpp
Labels: candidate: yes, preview, size: small

#8415 Feature: Add an option to disable tree growth completely
  src/lang/english.txt
  src/table/settings.ini
  src/tree_cmd.cpp
Labels: candidate: yes, preview, size: small

#8401 Change: Towns don't build dead-end road bridges
  src/town_cmd.cpp
Labels: candidate: yes, size: small, work: minor details

#7589 Change: Always apply inflation from 1920 to 2090, no matter the game start year.
  src/economy.cpp
Labels: candidate: needs considering, preview, size: small

#8234 Trees GUI improvements
  src/lang/english.txt
  src/tilehighlight_func.h
  src/tree_cmd.cpp
  src/tree_gui.cpp
  src/viewport.cpp
  src/widgets/tree_widget.h
  src/window_gui.h
Labels: candidate: yes, preview, size: large

#7890 Fix #6452: Reset only editable and visible settings from GUI
  src/ai/ai_gui.cpp
  src/script/script_config.cpp
  src/script/script_config.hpp
Labels: candidate: needs considering, preview, size: small

#8422 Change: Add some style to GameScript question windows depending on the type
  src/goal_gui.cpp
  src/lang/english.txt
Labels: candidate: yes, size: small

#8454 Fix #8297: Infrastructure counters for road tunnels, bridges, depots …
  src/economy_type.h
  src/road_cmd.cpp
  src/station_cmd.cpp
Labels: candidate: yes, size: small

#8470 Change #8325: Make engine reliability independent of introduction date
  src/engine.cpp
Labels: backport requested, bug, candidate: yes, size: trivial
