Repository OpenTTD/OpenTTD, pull requests merged in 2021-04, with the labels that each got.

#8916 Codechange: Suppress warnings when asserts are disabled
  src/3rdparty/squirrel/squirrel/sqcompiler.cpp
  src/3rdparty/squirrel/squirrel/sqstate.cpp
  src/3rdparty/squirrel/squirrel/sqvm.cpp
  src/blitter/factory.hpp
  src/pathfinder/npf/npf.cpp
Labels: backport requested

#8917 Codechange: Suppress warnings when asserts are disabled
  src/autoreplace_cmd.cpp
  src/driver.cpp
  src/engine.cpp
  src/industry_cmd.cpp
  src/misc/hashtable.hpp
  src/object_gui.cpp
  src/spritecache.cpp
  src/tgp.cpp
  src/town_cmd.cpp
  src/townname.cpp
  src/tunnelbridge_cmd.cpp
  src/vehicle.cpp
  src/vehiclelist.cpp
  src/widget.cpp
Labels: backport requested

#8924 Fix: building on Raspberry Pi failed because of const vs constexpr
  src/core/pool_type.hpp
Labels: backport requested

#8921 Add: [Actions] Debian Bullseye release build
  .github/workflows/release.yml
Labels: backport requested

#8925 Fix #8917: Release builds with asserts enabled
  src/3rdparty/squirrel/squirrel/sqstate.cpp
  src/3rdparty/squirrel/squirrel/sqvm.cpp
  src/spritecache.cpp
  src/tgp.cpp
  src/town_cmd.cpp
  src/townname.cpp
  src/vehicle.cpp
  src/widget.cpp
Labels: backport requested

#8928 Fix: Memory leak of airport tile layout in AirportChangeInfo (prop 0A)
  src/newgrf.cpp
Labels: backport requested

#8929 Fix: adjust object and rail station selection window padding to be consistent
  src/object_gui.cpp
  src/rail_gui.cpp
Labels: backport requested

#8906 Change: [CMake] Copy AI/GS compatibility files to build dir
  CMakeLists.txt
  bin/CMakeLists.txt
  bin/ai/CMakeLists.txt
  bin/game/CMakeLists.txt
  cmake/InstallAndPackage.cmake
Labels: backport requested

#8938 Codechange: Use COINIT_MULTITHREADED in CoInitializeEx
  src/music/dmusic.cpp
Labels: backport requested

#8944 Fix #8935: [OSX] Crash when clicking 'Save' due to wrongly-threaded OS call.
  src/video/cocoa/cocoa_v.mm
Labels: OS: MacOS, backport requested

#8934 Change: Disable NewGRF window apply button if no change was made
  src/newgrf_gui.cpp
  src/window_type.h
Labels: backport requested, preview

#8955 Change: [CMake] Improve 'In-source build' error message
  CMakeLists.txt
Labels: backport requested

#8926 Fix #8922: Show vehicle window for single vehicle in shared order grouping
  src/group_gui.cpp
  src/vehicle_gui.cpp
Labels: backport requested

#8959 Fix: [Network] State conditions for sending client info/quit packets
  src/network/network_server.cpp
Labels: backport requested

#8953 Fix: Use FluidSynth default soundfont
  src/music/fluidsynth.cpp
Labels: backport requested

#8948 Fix: Honor default soundfont for FluidSynth
  src/music/fluidsynth.cpp
Labels: backport requested

#8964 Fix: [CMake] Use the right run-time library depending on vcpkg triplet
  cmake/CompileFlags.cmake
Labels: backport requested

#8951 Fix graphical issues with dragging measurement tooltips in the viewport
  src/misc_gui.cpp
  src/viewport.cpp
  src/window_gui.h
Labels: backport requested

#8976 Fix #8930: [Win32] Don't handle printable keys on keydown if an edit box is in focus.
  src/video/win32_v.cpp
Labels: backport requested

#8989 Fix 70bc55cfd6e: snow line height was set while calculating desert line
  src/landscape.cpp
Labels: backport requested

#8990 Fix: [Win32] Font glyphs of certain widths broke
  src/os/windows/font_win32.cpp
Labels: backport requested

#8992 Fix #8956: Industry disaster news messages showed the wrong location
  src/disaster_vehicle.cpp
Labels: backport requested

#8993 Fix thread safety issues around the cursor and cursor sprites in the OpenGL backends
  src/video/cocoa/cocoa_ogl.mm
  src/video/opengl.cpp
  src/video/opengl.h
  src/video/sdl2_opengl_v.cpp
  src/video/win32_v.cpp
Labels: backport requested

#8994 Fix: Adjust scrolling interval of credits to account for text line height
  src/misc_gui.cpp
Labels: backport requested

#9014 Fix #9008: Validate starting year given on the command line.
  src/openttd.cpp
Labels: backport requested

#9016 Fix #9015: Don't set free space value if not requested.
  src/os/windows/win32.cpp
Labels: backport requested

#9007 Fix: Check for a validly mapped OpenGL screen buffer during driver init.
  src/video/sdl2_opengl_v.cpp
  src/video/win32_v.cpp
Labels: backport requested

#9022 Fix #8874: show a warning when a NewGRF scan is requested multiple times
  src/console_cmds.cpp
  src/openttd.cpp
  src/openttd.h
Labels: backport requested

#9032 Fix #9028: [OpenGL] Clear cursor cache on destroying the OpenGL backend.
  src/video/opengl.cpp
  src/video/opengl.h
Labels: component: OpenGL

#9037 Fix: Add virtual destructor to link graph Path.
  src/linkgraph/linkgraphjob.h
Labels: backport requested

#9042 Fix: Sizing of Multiplayer server list incorrect when GUI zoom doesn't match Font zoom.
  src/network/network_gui.cpp
Labels: backport requested

#9041 Change: Improve layout and spacing of vehicle group widgets.
  src/group_gui.cpp
Labels: backport requested

#9045 Fix: Corrupted savegame could crash the game by providing invalid gamelog enums.
  src/saveload/gamelog_sl.cpp
Labels: backport requested, security

#9046 Fix: Corrupted savegame could cause heap corruption by writing outside link graph edge matrix.
  src/saveload/linkgraph_sl.cpp
Labels: backport requested, security

#9044 Fix: Inconsistent button sizing on AI/GS setting window depending on scale settings.
  src/ai/ai_gui.cpp
Labels: backport requested

#9050 Fix #9042: Make multiplayer server list height auto-fill window.
  src/network/network_gui.cpp
Labels: backport requested

#9021 Fix: Do not unlock railtypes when enabling wagons with GameScript
  src/engine.cpp
Labels: backport requested

#9068 Fix: [CMake] Don't include regression AIs in bundles
  cmake/InstallAndPackage.cmake
Labels: backport requested

#9066 Fix: Auto-fill version details in rev.cpp and ottres.rc
  CMakeLists.txt
  cmake/scripts/FindVersion.cmake
  src/os/windows/ottdres.rc.in
  src/rev.cpp.in
Labels: backport requested

#9075 Fix: Scale rating minigraphs on station window list.
  src/station_gui.cpp
Labels: backport requested

#8546 Doc: provide a visual representation of the company colour ranges
  docs/company_colour_indexes.html
Labels: size: small, work: minor details

#9098 Fix #9097: Upper 16 bits of cargo base payment rate were discarded.
  src/cargotype.h
Labels: backport requested

#9106 Fix: [Network] Prevent stalling save game transfer when compression is slow
  src/network/network_server.cpp
Labels: backport requested

#9107 Fix: Count engine details text in lines rather than pixels.
  src/autoreplace_gui.cpp
  src/build_vehicle_gui.cpp
Labels: backport requested

#9124 Codechange: Use __attribute__ access none to silence GCC 11 -Wmaybe-uninitialized warnings
  src/stdafx.h
  src/string_func.h
Labels: backport requested

#9129 Fix b3003dd1: swap SERVER_GAME_INFO with CLIENT_GAME_INFO
  src/network/core/tcp_game.h
Labels: backport requested

#9133 Fix: Incorrect vertical alignment of icon and text in DropDownListIconItem.
  src/widgets/dropdown.cpp
  src/widgets/dropdown_type.h
Labels: backport requested

#9096 Fix: String validation could leave invalid Utf8 encoded strings
  src/string.cpp
Labels: backport requested

#9143 Remove: performance measurements in YAPF
  src/pathfinder/CMakeLists.txt
  src/pathfinder/follow_track.hpp
  src/pathfinder/npf/npf.cpp
  src/pathfinder/pf_performance_timer.hpp
  src/pathfinder/yapf/yapf.hpp
  src/pathfinder/yapf/yapf_base.hpp
  src/pathfinder/yapf/yapf_costcache.hpp
  src/pathfinder/yapf/yapf_costrail.hpp
  src/pathfinder/yapf/yapf_rail.cpp
Labels: backport requested
