Repository OpenTTD/OpenTTD, pull requests merged in 2021-08, with the labels that each got.

#9460 Fix: Use of unstable sort when distributing cargo production can caus…
  src/station_cmd.cpp
Labels: backport requested

#9455 Fix #9440: negative cargo payments not being handled right
  src/cargotype.h
  src/economy.cpp
  src/economy_type.h
Labels: needs review: NewGRF

#9464 Add: [Script] Basic information about loaded NewGRFs for scripts.
  src/script/api/CMakeLists.txt
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_newgrf.cpp
  src/script/api/script_newgrf.hpp
Labels: needs review: Script API

#9465 Fix 14f197c: [Script] int64 values don't fit into int
  src/script/api/script_list.cpp
Labels: backport requested

#9461 Fix 68f2213: Don't use GetPoolSize() for end of pool iterator
  src/core/pool_type.hpp
Labels: backport requested

#9468 Fix 8706dcd9: [Script] Byte-swap grfids to match normal expectations.
  src/script/api/script_newgrf.cpp
  src/script/api/script_newgrf.hpp
Labels: needs review: Script API

#9346 Feature: [NewGRF] Maximum curve speed modifier for rail vehicles
  src/engine_type.h
  src/newgrf.cpp
  src/newgrf_engine.cpp
  src/newgrf_engine.h
  src/newgrf_properties.h
  src/table/engines.h
  src/train.h
  src/train_cmd.cpp
Labels: needs review: NewGRF
