Repository OpenTTD/OpenTTD, pull requests merged in 2021-03, with the labels that each got.

#8821 Fix 937d60f2: Broken company colours for 40bpp-blitter.
  src/blitter/32bpp_optimized.cpp
Labels: component: OpenGL

#8822 Fix #8808: Crash on switching blitters due to double-mapping the video buffer
  src/video/cocoa/cocoa_ogl.mm
  src/video/cocoa/cocoa_v.mm
  src/video/cocoa/cocoa_wnd.mm
Labels: OS: MacOS, component: OpenGL

#8826 Fix #8825: [OpenGL] Don't clear cursor cache from the game loop thread.
  src/video/opengl.cpp
  src/video/opengl.h
Labels: component: OpenGL

#8700 Change: Recolour graph windows to brown
  src/ai/ai_gui.cpp
  src/graph_gui.cpp
  src/linkgraph/linkgraph_gui.cpp
  src/signs_gui.cpp
  src/widget.cpp
  src/widget_type.h
Labels: candidate: yes, preview

#8706 Feature: rail station class name filtering
  src/rail_gui.cpp
  src/widgets/rail_widget.h
Labels: preview

#8868 Fix: OSK layout not scaled for 2x or 4x GUI scale.
  src/osk_gui.cpp
Labels: backport requested

#8872 Fix: Recompute road/railtype availability after disabling the engine
  src/engine.cpp
Labels: backport requested

#8877 Fix #8871: [OpenGL] Initialize all buffers after resize and clear back buffer.
  src/video/opengl.cpp
  src/video/sdl2_opengl_v.cpp
  src/video/win32_v.cpp
Labels: backport requested, component: OpenGL

#8883 Fix f0f96e31: [OpenGL] Broken window resizing.
  src/video/opengl.cpp
Labels: backport requested, component: OpenGL

#8892 Fix: placing random trees in SE crashes the game
  src/genworld_gui.cpp
Labels: backport requested

#8885 Fix #8875: Filter string in station window breaks flow in user interface
  src/rail_gui.cpp
Labels: backport requested

#8876 Change: Do not disallow persistent buffer mapping on AMD GPUs, as it is actually faster.
  src/video/opengl.cpp
Labels: backport requested

#8893 Fix #8886: Don't try to resolve folders within tars named '.'
  src/fileio.cpp
Labels: backport requested

#8904 Fix #8803: Automatically removing signals on rail construction would …
  src/rail_cmd.cpp
Labels: backport requested
