Repository OpenTTD/OpenTTD, pull requests merged in 2021-09, with the labels that each got.

#8688 Feature: Hide block signals in GUI by default
  src/lang/english.txt
  src/rail_gui.cpp
  src/rail_gui.h
  src/settings_gui.cpp
  src/settings_table.cpp
  src/settings_type.h
  src/table/settings/gui_settings.ini
  src/widgets/rail_widget.h
Labels: preview

#8390 Add: [AI/GS] Missing water related functions and objects
  regression/regression/main.nut
  regression/regression/result.txt
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_marine.cpp
  src/script/api/script_marine.hpp
  src/script/api/script_tile.cpp
  src/script/api/script_tile.hpp
Labels: needs review: Script API

#9568 Add: allow gamescripts to build neutral objects
  src/command.cpp
  src/object_cmd.cpp
  src/script/api/CMakeLists.txt
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_objecttype.cpp
  src/script/api/script_objecttype.hpp
  src/script/api/script_objecttypelist.cpp
  src/script/api/script_objecttypelist.hpp
Labels: backport requested

#9576 Revert 7ca1793: Using Trackdir keyed node is not required, Exitdir keyed node still have the correct trackdir
  src/pathfinder/yapf/yapf_ship.cpp
Labels: backport requested

#9578 Change: Allow all tiles around docks to be docking tiles
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/station_cmd.cpp
Labels: backport requested

#9583 Add: Console command to list search directories for various things
  src/console_cmds.cpp
Labels: backport requested
