Repository OpenTTD/OpenTTD, pull requests merged in 2021-01, with the labels that each got.

#8476 Codechange: [OSX] Prevent the compiler from using SSE4 instructions unless we want to.
  cmake/CompileFlags.cmake
Labels: OS: MacOS, size: trivial

#8477 Fix: prevent clients making emergency saves twice if server disconnects
  src/network/network_client.cpp
Labels: candidate: yes, size: trivial

#8357 Codechange: Drop libxdg-basedir dependency in favour of finding the directories ourselves
  .github/workflows/ci-build.yml
  CMakeLists.txt
  cmake/FindXDG_basedir.cmake
  src/fileio.cpp
  src/fileio_type.h
  src/stdafx.h
Labels: OS: Linux, candidate: yes, size: small, work: minor details

#8478 Add: [CMake] Explicitly support txz for Arch Linux
  cmake/InstallAndPackage.cmake
Labels: OS: Linux, size: small

#8484 Fix: [OSX] Register fonts loaded directly from disk for text layout
  src/fontcache.cpp
  src/os/macosx/string_osx.cpp
  src/os/macosx/string_osx.h
Labels: OS: MacOS

#8466 Fix: GetCurveSpeedLimit needs railtype from current tile
  src/train_cmd.cpp
Labels: candidate: yes, component: NewGRF, needs review: NewGRF, size: trivial

#8458 Fixes for issues with rotated (non-rectangular) airports
  src/aircraft_cmd.cpp
Labels: candidate: yes, needs review: mad man, size: small

#8439 Feature: Make town bridge max length a function of its population
  src/town_cmd.cpp
Labels: candidate: yes, size: small

#8274 Feature: option to auto remove signals when in the way during rail co…
  src/lang/english.txt
  src/rail_cmd.cpp
  src/rail_gui.cpp
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings.ini
Labels: candidate: yes, preview, size: large

#7947 Fix #7945: Add cost of clearing the sloped tile when placing a dock
  regression/regression/result.txt
  src/station_cmd.cpp
Labels: candidate: most likely, size: small

#8513 Fix: for arctic and tropic, make sure we have at least a few hills
  src/tgp.cpp
  src/tile_type.h
Labels: preview

#8169 Fix #8153: Report autoreplace failure when new vehicle cannot carry the cargo
  src/autoreplace_cmd.cpp
  src/lang/english.txt
Labels: candidate: yes, size: small

#8473 Add: Towns can build tunnels
  src/town_cmd.cpp
Labels: candidate: yes, preview, size: small, work: minor details

#8535 Fix #8506: Towns shouldn't add junctions to NewGRF roads they cannot build
  src/town_cmd.cpp
Labels: preview

#8538 Remove: warning in cheat window
  src/cheat_gui.cpp
  src/lang/english.txt
  src/widgets/cheat_widget.h
Labels: preview

#8544 Add: [Script] ScriptCargo::GetName, to get the human readable name of a cargo
  regression/regression/main.nut
  regression/regression/result.txt
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_cargo.cpp
  src/script/api/script_cargo.hpp
Labels: candidate: yes, needs review: Script API, size: small

#8531 Fix #7619: nudge fast planes sooner towards their target
  src/aircraft_cmd.cpp
Labels: candidate: yes, needs review: mad man, size: small

#8557 Change: darken the background of all graph to increase contrast
  src/graph_gui.cpp
Labels: preview

#8540 Fix eeb88e8: Trains reversed while paused do not correctly update sprite bounds
  src/saveload/vehicle_sl.cpp
  src/ship_cmd.cpp
  src/vehicle.cpp
  src/vehicle_base.h
  src/viewport.cpp
  src/viewport_func.h
Labels: candidate: yes, needs review: NewGRF, size: large

#8591 Fix #8589, 653e7fa548: Motion counter is NewGRF-visible but not saved, leading to desyncs.
  src/saveload/saveload.h
  src/saveload/vehicle_sl.cpp
Labels: component: NewGRF

#8590 Fix recent NewGRF spec addition to make it less surprising/arbitrary
  src/industry_cmd.cpp
  src/industrytype.h
Labels: needs review: NewGRF

#8547 Doc: add a png representation of the palette overlaid with indexes (dec)
  docs/palettes/palette_key.png
Labels: needs review
