Repository OpenTTD/OpenTTD, pull requests merged in 2021-02, with the labels that each got.

#8622 Fix 81d335b081: Use non-pulsating red highlight for coverage
  src/viewport.cpp
Labels: preview

#8655 Fix: [Emscripten] open links in browser
  os/emscripten/pre.js
  src/os/unix/unix.cpp
Labels: preview

#8550 Feature: "Remove all industries" button in scenario editor
  src/industry_gui.cpp
  src/lang/english.txt
  src/widgets/industry_widget.h
Labels: candidate: yes, preview, size: small

#8669 Change: Make order window hotkeys toggle for load & unload variants
  src/order_gui.cpp
Labels: preview

#8578 Fix: Stopped ships shouldn't block depots
  src/ship_cmd.cpp
Labels: candidate: most likely, size: small

#8603 Feature: Object class selection string filtering
  src/object_gui.cpp
  src/widgets/object_widget.h
Labels: preview
