Repository OpenTTD/OpenTTD, pull requests merged in 2021-05, with the labels that each got.

#9159 Fix #9152, #9153: screenshot command showed error messages when successful
  src/screenshot.cpp
Labels: backport requested

#9154 Fix d4f0b6f4: [CMake] CMAKE_PROJECT_VERSION_XXX are not in CMake 3.9
  CMakeLists.txt
Labels: backport requested

#9166 Change: [Actions] Add a 2 minutes timeout for regression test
  .github/workflows/ci-build.yml
Labels: backport requested

#9164 Fix: Don't consider regression AIs when starting a random AI
  regression/regression/info.nut
  regression/stationlist/info.nut
Labels: backport requested

#9175 Fix: Crash when extra viewport height is zero with sign in view.
  src/widget.cpp
Labels: backport requested

#9176 Fix: [Network] Reading beyond the length of the server's ID when hashing passwords
  src/network/network.cpp
Labels: backport requested

#9088 Fix: [NewGRF] industry variables 65 and 66, object variable 46
  src/newgrf_industries.cpp
  src/newgrf_object.cpp
Labels: backport requested, needs review: NewGRF

#9140 Codechange: Acquire video buffer before taking game state lock to prevent erratic fast forward behaviour
  src/video/video_driver.cpp
Labels: backport requested

#9182 Fix #9113: Assertion failure when removing airport with order backup
  src/station_cmd.cpp
Labels: backport requested

#9183 Fix #9174: Don't update text effect if it has been reset.
  src/texteff.cpp
Labels: backport requested

#9184 Fix: Query windows may be partially drawn initially.
  src/misc_gui.cpp
Labels: backport requested

#9181 Fix #9117, 04ce1f07: [Fluidsynth] Infinite wait when stopping song
  src/music/fluidsynth.cpp
Labels: backport requested

#9219 Fix: Apply unscaled padding to Viewport inside WWT_INSET.
  src/industry_gui.cpp
  src/news_gui.cpp
  src/town_gui.cpp
  src/vehicle_gui.cpp
  src/waypoint_gui.cpp
  src/widget.cpp
Labels: backport requested

#9225 Fix: [MinGW] Reapply 48fd7b27 to fix launch on Windows 7 x64
  CMakeLists.txt
Labels: backport requested

#9247 Fix: [Actions] Annotations not shown for MSVC
  cmake/CompileFlags.cmake
Labels: backport requested

#9232 Fix 91b8ce07: dedicated servers could no longer create screenshots
  src/video/dedicated_v.cpp
  src/video/video_driver.hpp
Labels: backport requested

#9187 Fix #9186: Fix incorrect bounding box height causing station sprite glitch.
  src/table/station_land.h
Labels: backport requested

#9275 Fix #9267, 47a99bb: [Squirrel] Heap use after free
  src/3rdparty/squirrel/squirrel/sqclass.cpp
Labels: backport requested

#9271 Fix: Encountering two-way red signals could prune unrelated branches.
  src/pathfinder/yapf/yapf_base.hpp
  src/pathfinder/yapf/yapf_costrail.hpp
Labels: needs review: mad man

#9278 Fix #9264: Do not attach temporary wagons to free wagon chains when autoreplacing
  src/train_cmd.cpp
Labels: backport requested

#9280 Fix: Do not send vehicles towards incomplete PF nodes
  src/pathfinder/yapf/yapf_base.hpp
Labels: needs review: mad man

#9307 Fix: artificially limit heightmap sizes to something reasonable
  src/heightmap.cpp
Labels: backport requested

#9318 Fix #9316, 64eddaeb: at about 250.000 inhabitants the bridge length limit check overflows
  src/town_cmd.cpp
Labels: backport requested
