Repository OpenTTD/OpenTTD, pull requests merged in 2022-12, with the labels that each got.

#10235 Fix #10218: Sloped river tiles need water both up and downstream
  src/landscape.cpp
Labels: size: small

#10233 Fix #10208: allow to use specific underlay for road/tram tunnels
  src/road.h
  src/road_cmd.cpp
  src/road_func.h
  src/tunnelbridge_cmd.cpp
Labels: size: small, needs review: NewGRF

#10262 Change: Support flipping shorter engines without NewGRF support.
  src/engine_type.h
  src/newgrf.cpp
  src/table/engines.h
  src/train.h
  src/train_cmd.cpp
  src/vehicle_gui.cpp
Labels: preview, needs review: NewGRF

#10265 Feature: Ctrl-click to bulk edit timetable speeds/waiting times
  src/command_type.h
  src/lang/english.txt
  src/timetable_cmd.cpp
  src/timetable_cmd.h
  src/timetable_gui.cpp
Labels: preview, size: small

#10203 Fix #10198: Rearrange Intro GUI to make button rows narrower
  src/intro_gui.cpp
Labels: size: trivial

#10215 Feature: Expand all towns in the scenario editor
  src/lang/english.txt
  src/town_gui.cpp
  src/widgets/town_widget.h
Labels: preview, size: trivial

#10200 Fix: Bad alignment of button icons when using the original baseset.
  media/baseset/orig_extra.grf
  media/baseset/orig_extra/fix_gui_icons.nfo
  media/baseset/orig_extra/fix_gui_icons.png
  media/baseset/orig_extra/orig_extra.nfo
Labels: size: small, needs review: NewGRF

#10230 Fix #10224: Don't fiddle with fast-forward when saving.
  src/saveload/saveload.cpp
Labels: size: trivial

#9745 Fix #9720: Delay start of GS/AI to after loading of savegame
  src/ai/ai.hpp
  src/ai/ai_core.cpp
  src/game/game.hpp
  src/game/game_core.cpp
  src/saveload/afterload.cpp
  src/saveload/ai_sl.cpp
  src/saveload/game_sl.cpp
  src/script/script_config.cpp
  src/script/script_config.hpp
  src/script/script_instance.cpp
  src/script/script_instance.hpp
Labels: component: AI/Game script (squirrel), needs review: Script API
