Repository OpenTTD/OpenTTD, pull requests merged in 2022-02, with the labels that each got.

#9761 Change: add a timestamp in name of crash files
  src/crashlog.cpp
  src/crashlog.h
  src/os/macosx/crashlog_osx.cpp
  src/os/windows/crashlog_win.cpp
Labels: backport requested

#9812 Fix #9811, 9156d7b: Use the NewGRF-defined vehicle center when dragging ships and aircraft.
  src/vehicle_gui.cpp
Labels: bug, backport requested

#9536 Change: Deliver cargo to the closest industry first
  src/cargomonitor.cpp
  src/economy.cpp
  src/industry_cmd.cpp
  src/station.cpp
  src/station_base.h
  src/subsidy.cpp
Labels: backport requested, preview

#9808 Fix: do not let shares in the company taking over another company disappear
  src/economy.cpp
Labels: backport requested
