Repository OpenTTD/OpenTTD, pull requests merged in 2022-10, with the labels that each got.

#10052 Cleanup: Remove unused flag sprites.
  media/baseset/openttd.grf
  media/baseset/openttd/flags.nfo
  media/baseset/openttd/flags.png
  media/baseset/openttd/openttd.nfo
  src/network/network_gui.cpp
  src/newgrf.cpp
  src/table/sprites.h
Labels: needs review: NewGRF

#9891 Feature: Towns don't build parallel, redundant bridges
  src/town_cmd.cpp
Labels: preview

#9996 Fix #9995: Adjust viewport zoom level for HiDPI displays
  src/industry_gui.cpp
  src/main_gui.cpp
  src/news_gui.cpp
  src/town_gui.cpp
  src/vehicle_gui.cpp
  src/viewport_gui.cpp
  src/waypoint_gui.cpp
  src/zoom_func.h
  src/zoom_type.h
Labels: preview

#9628 Feature: Wide rivers
  src/direction_type.h
  src/landscape.cpp
Labels: preview, size: small
