Repository OpenTTD/OpenTTD, pull requests merged in 2022-11, with the labels that each got.

#10120 Fix #10117: Decrement object burst limit after build check
  src/object_cmd.cpp
Labels: size: trivial

#9931 Feature: Multi-track level crossings
  src/pbs.cpp
  src/rail_cmd.cpp
  src/road_cmd.cpp
  src/road_func.h
  src/roadveh_cmd.cpp
  src/roadveh_cmd.h
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/table/road_land.h
  src/train_cmd.cpp
Labels: preview

#10138 Fix 03cc0d6: Mark level crossings dirty when removing road from them, not from bridges
  src/road_cmd.cpp
Labels: size: trivial

#10137 Fix #10135: Cost of building multiple objects might not match test
  src/object_cmd.h
Labels: size: trivial

#9727 Feature #9059: Add buttons to toggle music in the Game Options menu.
  src/settings_gui.cpp
  src/widgets/settings_widget.h
Labels: waiting on author, preview, size: trivial

#8514 Change: Allow to build dock on clearable watered object tiles
  src/station_cmd.cpp
Labels: size: small, candidate: needs considering

#10110 Feature: Hotkey to honk a vehicle's horn
  src/newgrf_sound.cpp
  src/newgrf_sound.h
  src/ship.h
  src/ship_cmd.cpp
  src/sound.cpp
  src/train.h
  src/train_cmd.cpp
  src/vehicle_base.h
  src/vehicle_gui.cpp
  src/widgets/vehicle_widget.h
Labels: preview, size: small

#10058 Feature: [UI] Split AI/Game Script configuration windows and add them to world gen window
  src/ai/ai_gui.cpp
  src/ai/ai_gui.hpp
  src/game/CMakeLists.txt
  src/game/game_gui.cpp
  src/game/game_gui.hpp
  src/genworld_gui.cpp
  src/intro_gui.cpp
  src/lang/english.txt
  src/toolbar_gui.cpp
  src/widgets/CMakeLists.txt
  src/widgets/ai_widget.h
  src/widgets/game_widget.h
  src/widgets/genworld_widget.h
  src/widgets/intro_widget.h
  src/window_type.h
Labels: preview

#10152 Feature: Allow AI/GS to be fully modified in scenario editor
  src/ai/ai_gui.cpp
  src/game/game_gui.cpp
  src/settings_type.h
Labels: size: trivial

#9928 Change: Remove scrollbar from town authority actions panel
  src/lang/english.txt
  src/script/api/script_town.cpp
  src/table/settings/economy_settings.ini
  src/town.h
  src/town_cmd.cpp
  src/town_gui.cpp
Labels: preview

#10157 Fix #10154: Don't inconsistently set random company face in network games
  src/company_cmd.cpp
Labels: size: trivial

#10168 Change: Requested changes to the Finance GUI
  src/company_gui.cpp
  src/lang/english.txt
Labels: size: trivial

#10173 Change: Allow building canal by area outside editor
  src/dock_gui.cpp
  src/water_cmd.cpp
Labels: size: trivial

#8304 Feature: Show the cargoes the vehicles can carry in the list window.
  src/lang/english.txt
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings/gui_settings.ini
  src/vehicle_gui.cpp
Labels: preview, size: trivial, candidate: yes

#8425 Feature: Contextual actions for vehicles grouped by shared orders
  src/depot_gui.cpp
  src/group_gui.cpp
  src/lang/english.txt
  src/order_gui.cpp
  src/vehicle.cpp
  src/vehicle_func.h
  src/vehicle_gui.cpp
  src/vehicle_gui.h
  src/window_gui.h
Labels: preview, size: small
