Repository OpenTTD/OpenTTD, pull requests merged in 2023-09, with the labels that each got.

#10755 Feature: Setting to disallow level crossings with competitors
  src/lang/english.txt
  src/rail_cmd.cpp
  src/road_cmd.cpp
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings/world_settings.ini
Labels: preview, candidate: needs considering

#11265 Fix: [CI] preview flow can't install latest version of npm
  .github/workflows/preview-build.yml
Labels: preview

#11268 Fix: asserts unintentially being partially disabled in release-builds
  src/stdafx.h
Labels: preview

#10680 Fix #10600: 'Replace Vehicles' shows numbers >999
  src/build_vehicle_gui.cpp
Labels: candidate: yes

#11294 Fix: also apply cargo filters on shared groups in vehicle listing
  src/vehicle_gui.cpp
Labels: preview

#11283 Fix: only count distance traveled in vehicles for cargo payment
  src/cargoaction.cpp
  src/cargoaction.h
  src/cargopacket.cpp
  src/cargopacket.h
  src/economy.cpp
  src/saveload/cargopacket_sl.cpp
  src/saveload/saveload.h
  src/vehicle.cpp
Labels: preview
