Repository OpenTTD/OpenTTD, pull requests merged in 2023-07, with the labels that each got.

#9642 Feature: Orientation of rail and road depots can be changed
  regression/regression/main.nut
  regression/regression/result.txt
  src/rail_cmd.cpp
  src/rail_map.h
  src/road_cmd.cpp
  src/road_map.h
Labels: preview

#11113 Fix 021c45c: [CMake] detection and use of nlohmann-json for emscripten
  .github/workflows/ci-build.yml
  .github/workflows/preview_build.yml
  os/emscripten/cmake/Findnlohmann_json.cmake
Labels: preview

#11125 Fix #11115: Focus the abandon game/exit game windows
  src/intro_gui.cpp
  src/misc_gui.cpp
  src/textbuf_gui.h
Labels: preview

#11076 Changing exclusive transport rights
  src/lang/english.txt
  src/town_cmd.cpp
Labels: candidate: needs considering

#10204 Feature: Add alternative setting for right-click close window option to exclude pinned windows
  src/lang/english.txt
  src/settings.cpp
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings/gui_settings.ini
  src/window.cpp
Labels: preview, size: trivial

#11068 Feature: Set default company secondary colour for new games
  src/lang/english.txt
  src/openttd.cpp
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings/gui_settings.ini
Labels: preview

#11102 Change: Only show platform stopping location in orders when other than default
  src/lang/english.txt
  src/order_gui.cpp
  src/table/settings/gui_settings.ini
Labels: preview, size: trivial
