Repository OpenTTD/OpenTTD, pull requests merged in 2023-02, with the labels that each got.

#10451 Fix: Ensure logo for Windows Store common assets package is named correctly
  os/windows/winstore/generate-assets.ps1
Labels: backport requested

#10462 Fix #10461, Fix #10280: Town actions GUI issues
  src/town_gui.cpp
Labels: backport requested

#10466 Fix #10465: Delay closing of network join progress window
  src/network/network_client.cpp
Labels: backport requested

#10488 Fix: [Actions] vcpkg needs pkg-config to build zlib on macOS
  .github/workflows/ci-build.yml
  .github/workflows/release-macos.yml
Labels: backport requested

#10487 Fix #10486: [Script] Debug window requires AIs to be started before GS
  src/saveload/afterload.cpp
Labels: backport requested

#10386 Fix: Some Script::IsValidVehicle checks need to be complemented with IsPrimaryVehicle
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_group.cpp
  src/script/api/script_group.hpp
  src/script/api/script_order.cpp
  src/script/api/script_order.hpp
  src/script/api/script_stationlist.cpp
  src/script/api/script_vehicle.cpp
  src/script/api/script_vehicle.hpp
  src/script/api/script_vehiclelist.cpp
  src/script/api/script_waypointlist.cpp
Labels: needs review: Script API

#10496 Change: Avoid crashing to the side of a train
  src/road_cmd.cpp
  src/train.h
  src/train_cmd.cpp
Labels: backport requested, preview

#10497 Revert 92c7551: Line drawing algorithm fix broke other cases
  src/blitter/common.hpp
Labels: regression

#10144 Add: NewGRF road stops
  docs/landscape.html
  docs/landscape_grid.html
  src/CMakeLists.txt
  src/base_station_base.h
  src/cheat_gui.cpp
  src/date.cpp
  src/economy.cpp
  src/newgrf.cpp
  src/newgrf.h
  src/newgrf_airporttiles.cpp
  src/newgrf_animation_base.h
  src/newgrf_callbacks.h
  src/newgrf_debug_gui.cpp
  src/newgrf_house.cpp
  src/newgrf_industrytiles.cpp
  src/newgrf_object.cpp
  src/newgrf_roadstop.cpp
  src/newgrf_roadstop.h
  src/newgrf_station.cpp
  src/road_cmd.h
  src/road_gui.cpp
  src/saveload/compat/station_sl_compat.h
  src/saveload/saveload.h
  src/saveload/station_sl.cpp
  src/script/api/script_road.cpp
  src/station.cpp
  src/station_base.h
  src/station_cmd.cpp
  src/station_cmd.h
  src/station_map.h
  src/table/newgrf_debug_data.h
  src/vehicle.cpp
  src/widgets/road_widget.h
Labels: component: NewGRF, size: large, needs review: NewGRF

#7729 Add: Allow autoreplace with same model vehicle
  src/autoreplace.cpp
  src/autoreplace_cmd.cpp
Labels: size: small, candidate: needs considering

#10471 Fix #10469, 5e14a20: [Script] League Table rating element is a int64 everywhere else
  src/league_base.h
  src/saveload/league_sl.cpp
  src/saveload/saveload.h
Labels: backport requested

#10018 Codechange: Don't store tree counter in the map array
  docs/landscape.html
  regression/regression/result.txt
  src/saveload/afterload.cpp
  src/tree_cmd.cpp
  src/tree_map.h
Labels: preview

#9852 Fix #9810: 'Rebuilding' a through road stop costs money.
  src/station_cmd.cpp
  src/waypoint_cmd.cpp
Labels: preview, size: small
