Repository OpenTTD/OpenTTD, pull requests merged in 2023-01, with the labels that each got.

#10247 Update: Title game for 13.0 release
  media/baseset/opntitle.dat
Labels: preview, size: trivial

#10305 Fix #10304, fe30f66: [Scripts] Don't start GS in intro
  src/game/game_core.cpp
Labels: backport requested

#10316 Fix: do not allow more palette colours than there are indices for the colours
  src/bmp.cpp
Labels: security, backport requested

#10321 Fix: prevent corrupted GRF files to allocate stupid amounts of memory
  src/spriteloader/grf.cpp
Labels: backport requested

#10315 Fix: Don't assume engclass 2 should be elrail.
  src/elrail.cpp
  src/engine_type.h
  src/newgrf.cpp
  src/table/engines.h
Labels: backport requested

#10328 Fix #10309: [SDL] Uninitialized width and height when turning off full screen
  src/video/sdl2_v.cpp
Labels: backport requested

#10332 Fix #10331: Starting new company during load must happen after AI start.
  src/saveload/afterload.cpp
Labels: backport requested

#10336 Fix #10335: Set initial scrollbar count for object GUI.
  src/object_gui.cpp
Labels: backport requested

#10093 Change: Remove land generator setting from World Generation GUI
  src/genworld_gui.cpp
  src/lang/english.txt
Labels: preview, size: trivial

#10338 Fix #10333, c53f29d: Only show industry prospecting errors to local company
  src/industry_cmd.cpp
Labels: backport requested, size: trivial

#10346 Fix: Link variants to parents when finalising engines.
  src/newgrf.cpp
Labels: backport requested

#10342 Feature: Press Ctrl to build a diagonal area of trees
  src/lang/english.txt
  src/script/api/script_tile.cpp
  src/tree_cmd.cpp
  src/tree_cmd.h
  src/tree_gui.cpp
Labels: preview, size: small

#10340 Feature: Set a custom number of industries in map generation window
  src/genworld_gui.cpp
  src/industry_cmd.cpp
  src/settings_type.h
  src/table/settings/difficulty_settings.ini
  src/table/settings/world_settings.ini
Labels: preview, size: trivial

#10348 Fix: Various Wide River issues
  src/landscape.cpp
Labels: backport requested, size: trivial

#10326 Fix #10032: Capacities of articulated vehicles in build window
  src/articulated_vehicles.cpp
  src/autoreplace_cmd.cpp
  src/autoreplace_gui.cpp
  src/build_vehicle_gui.cpp
  src/economy.cpp
  src/engine_func.h
  src/script/api/script_vehicle.cpp
  src/train_cmd.h
  src/train_gui.cpp
  src/vehicle_cmd.cpp
  src/vehicle_cmd.h
  src/vehicle_gui.cpp
  src/vehicle_gui.h
Labels: backport requested

#10356 Fix #10057: FallbackParagraphLayout fails to properly wrap
  src/gfx_layout.cpp
Labels: backport requested

#10354 Fix #10177: company list password padlock showed after switching to single player
  src/network/network.cpp
Labels: backport requested

#10357 Fix #9865: removing files with the console always failed
  src/console_cmds.cpp
Labels: backport requested

#10364 Fix #10363: CargoDist setting helptext shouldn't suggest symmetric distribution for diamonds in subtropic
  src/lang/english.txt
Labels: size: trivial

#10369 Fix #10368, Fix 994bf19: server restarting game caused clients to hit assertion
  src/highscore_gui.cpp
Labels: backport requested

#10365 Fix #10362: NewGRF bridges without speed limits.
  src/bridge_gui.cpp
  src/lang/english.txt
  src/newgrf.cpp
  src/tunnelbridge_cmd.cpp
Labels: component: NewGRF

#10227 Fix 3c047b1: AIGroup.GetProfitLastYear could get values different than those displayed in GUI
  src/autoreplace_cmd.cpp
  src/group.h
  src/group_cmd.cpp
  src/group_gui.cpp
  src/vehicle.cpp
Labels: backport requested, size: small

#10378 Fix #10377, Fix 94167df: bad sorting of rail vehicles when primary variant is missing
  src/build_vehicle_gui.cpp
  src/engine_gui.cpp
  src/engine_gui.h
Labels: backport requested

#10400 Fix #10395: When loading old saves, don't forcibly bar level crossings
  src/saveload/afterload.cpp
Labels: backport requested, size: trivial

#10404 Fix #10220: Don't select unselectable engine as default.
  src/build_vehicle_gui.cpp
Labels: backport requested

#10410 Fix #10255: Reduce basic thickness of linkgraph GUI lines
  src/main_gui.cpp
Labels: backport requested, preview

#9924 Fix 7e1e275: Measure AI Collect Garbage performance
  src/ai/ai_core.cpp
Labels: size: trivial

#10433 Fix #10361, fe30f66: Don't try to give saved data to a dead script
  src/script/script_instance.cpp
Labels: backport requested
