Repository OpenTTD/OpenTTD, pull requests merged in 2023-06, with the labels that each got.

#10916 Fix: Wayland crash on startup due to Pango also using FontConfig
  src/os/unix/font_unix.cpp
Labels: backport requested

#10919 Fix: [SDL] unify the way X11 and Wayland handle mouse events
  src/gfx.cpp
  src/gfx_type.h
  src/video/allegro_v.cpp
  src/video/cocoa/cocoa_wnd.mm
  src/video/sdl2_v.cpp
  src/video/sdl_v.cpp
  src/video/win32_v.cpp
Labels: preview

#10920 Add: [Linux] change default scroll mode to non-mouse-lock
  src/lang/english.txt
  src/table/settings/gui_settings.ini
Labels: backport requested

#10928 Fix: disable hardware acceleration when GPU driver crashed the game last attempt
  src/driver.cpp
  src/driver.h
  src/lang/english.txt
  src/video/video_driver.cpp
Labels: backport requested

#10926 Fix #10502: Refit engine before attaching free wagons.
  src/train.h
  src/train_cmd.cpp
  src/train_cmd.h
  src/vehicle_cmd.cpp
Labels: backport requested

#10934 Fix: crash when not even a single row fits for dropdowns on low resolution screens
  src/widgets/dropdown.cpp
Labels: backport requested

#10932 Fix: crash when window can't be placed on low resolution screens.
  src/core/math_func.hpp
  src/misc_gui.cpp
  src/tests/math_func.cpp
Labels: backport requested

#10933 Fix: crash with tooltip on low resolution screens
  src/misc_gui.cpp
Labels: backport requested

#10942 Fix: [Win32] position window in center of workspace of primary display
  src/video/win32_v.cpp
Labels: backport requested

#10979 Fix: Don't restore backed up vehicle name if it's no longer unique.
  src/order_backup.cpp
  src/vehicle_cmd.cpp
  src/vehicle_func.h
Labels: backport requested

#10985 Fix 07add7a9: [Win32] use full monitor resolution for fullscreen
  src/video/win32_v.cpp
Labels: backport requested

#11000 Fix #10987: Double-close of dropdown stopped land-info tool working as default.
  src/console_gui.cpp
  src/osk_gui.cpp
  src/widgets/dropdown.cpp
  src/window.cpp
  src/window_gui.h
Labels: backport requested

#10890 Feature: Create group of vehicles from manage vehicle list button.
  src/CMakeLists.txt
  src/autoreplace_cmd.cpp
  src/group_cmd.cpp
  src/group_cmd.h
  src/group_gui.cpp
  src/lang/english.txt
  src/order_backup.cpp
  src/script/api/script_group.cpp
  src/vehicle_cmd.cpp
  src/vehicle_cmd.h
  src/vehicle_gui.cpp
  src/vehicle_gui_base.h
  src/vehiclelist_cmd.h
Labels: preview

#11044 Fix #11043: Don't choose toolbar dropdown option if focus is lost.
  src/widgets/dropdown.cpp
Labels: backport requested

#11040 Fix: #10917 move interest payment before stat generation
  src/economy.cpp
Labels: waiting on author

#11070 Fix: Setting tree lines drawn incorrectly for RTL languages.
  src/settings_gui.cpp
Labels: backport requested

#11017 Change: Make terraforming point selection sprite visible at >2x zoom out
  src/smallmap_gui.cpp
  src/table/sprites.h
  src/viewport.cpp
Labels: preview
