Repository OpenTTD/OpenTTD, pull requests merged in 2023-04, with the labels that each got.

#10601 Fix: NewGRF Action3 (+others) validation
  src/newgrf.cpp
Labels: backport requested

#10594 Feature: Separate rail/road and sea/air velocity units, and add knots.
  src/bridge_gui.cpp
  src/build_vehicle_gui.cpp
  src/engine_gui.cpp
  src/lang/english.txt
  src/misc_gui.cpp
  src/order_gui.cpp
  src/rail_gui.cpp
  src/road_gui.cpp
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/settings_gui.cpp
  src/settings_type.h
  src/strings.cpp
  src/strings_func.h
  src/table/settings/locale_settings.ini
  src/timetable_gui.cpp
  src/vehicle_gui.cpp
Labels: preview

#10634 Codechange: Use cached name for all station/industry/town name formatting.
  src/strings.cpp
Labels: preview

#10657 Fix: Update some network documentation to match the new command system
  src/network/core/tcp_admin.h
  src/network/core/tcp_game.h
Labels: backport requested

#10618 Change: Allow overbuilding station and waypoint tiles
  src/station_cmd.cpp
  src/waypoint_cmd.cpp
Labels: size: trivial

#10673 Fix #10665: CheckEngines should ignore wagons
  src/engine.cpp
Labels: preview

#10669 Fix #10627: Houses subsitute specs should only be copied on first definition.
  src/newgrf.cpp
Labels: needs review: NewGRF

#10695 Fix #8177: Ships with max speed overflow to near-zero speed
  src/ship_cmd.cpp
Labels: backport requested

#10730 Fix: FormatArrayAsHex returns gibberish instead of a hex array
  src/string.cpp
  src/tests/string_func.cpp
Labels: backport requested
