Repository OpenTTD/OpenTTD, pull requests merged in 2023-05, with the labels that each got.

#10674 Change: Split Game options into General, Graphics, and Sound tabs.
  src/lang/english.txt
  src/settings_gui.cpp
  src/widgets/settings_widget.h
Labels: preview

#10752 Fix: [Win32] Wrong multi-line text layout due to incorrect whitespace
  src/os/windows/string_uniscribe.cpp
Labels: OS: Windows, backport requested

#10775 Fix: [Win32] Text line breaking did not properly handle punctuation characters.
  src/os/windows/string_uniscribe.cpp
Labels: OS: Windows, backport requested

#10806 Feature: Show the number of industries already built in the Fund New Industry window
  src/industry_cmd.cpp
  src/industry_gui.cpp
Labels: preview

#10883 Fix: Check max member count in squirrel classes
  src/3rdparty/squirrel/squirrel/sqclass.cpp
  src/3rdparty/squirrel/squirrel/sqclass.h
Labels: backport requested
