Repository OpenTTD/OpenTTD, pull requests merged in 2024-09, with the labels that each got.

#12924 Fix 208952f: incorrect truncation in string setting validation
  src/settings.cpp
Labels: backport requested

#12890 Change: [NewGRF] Place all 8 bits of station tile layout in var 40/41/46/47/49.
  src/newgrf_station.cpp
Labels: needs review: NewGRF

#10409 Feature: Import town data from JSON file
  docs/importing_town_data.md
  src/fileio_type.h
  src/fios.cpp
  src/fios.h
  src/fios_gui.cpp
  src/genworld.cpp
  src/genworld.h
  src/lang/english.txt
  src/town_cmd.cpp
  src/town_gui.cpp
  src/widgets/town_widget.h
Labels: candidate: yes

#12950 Fix fcf8693c4f: Remove 100 byte limit for parsing string command parameters
  src/strgen/strgen_base.cpp
Labels: preview

#12938 Add: Overlay cargo icon in vehicle/depot list when holding shift+ctrl.
  src/aircraft_gui.cpp
  src/depot_gui.cpp
  src/group_gui.cpp
  src/lang/english.txt
  src/roadveh_gui.cpp
  src/ship_gui.cpp
  src/train_gui.cpp
  src/vehicle_gui.cpp
  src/vehicle_gui_base.h
Labels: preview

#12646 Change: Use default NewGRF cargo translation table.
  src/cargotype.cpp
  src/cargotype.h
  src/newgrf.cpp
  src/newgrf_cargo.cpp
  src/newgrf_cargo.h
Labels: preview
