Repository OpenTTD/OpenTTD, pull requests merged in 2024-11, with the labels that each got.

#12992 Codechange: Simplified YAPF ship region node
  src/pathfinder/yapf/yapf_ship_regions.cpp
Labels: needs review: mad man

#13090 [NewGRF] More options for setting vehicle refit masks
  src/newgrf.cpp
  src/newgrf_callbacks.h
Labels: needs review: NewGRF

#13112 Change: Show company finances column if it has any values in it.
  src/cheat_gui.cpp
  src/company_cmd.cpp
  src/company_gui.cpp
Labels: preview
