Repository OpenTTD/OpenTTD, pull requests merged in 2024-03, with the labels that each got.

#12173 Update: Developer credits
  CREDITS.md
  src/misc_gui.cpp
Labels: backport requested

#12201 Fix #12196: always show selected content, even when filtering and disable "select upgrade" button when filtering
  src/network/network_content_gui.cpp
Labels: backport requested

#12155 Fix f6dd505: Only reset unbunching departure data in the correct depot
  src/vehicle.cpp
Labels: backport requested

#12199 Codechange: Don't use NOT_REACHED() when catching unhandled thread exceptions
  src/thread.h
Labels: backport requested

#12207 Fix #12195: Reset cursor when no Object is selected
  src/object_gui.cpp
Labels: backport requested

#12208 Fix #12076: Do not allow 'join' command on dedicated servers
  src/console_cmds.cpp
Labels: backport requested

#12210 Fix #12147: reset all saved settings to their default before loading a game
  src/saveload/settings_sl.cpp
  src/settings.cpp
  src/settings_internal.h
Labels: backport requested

#12158 Fix #12154: Incorrect calendar day lengths with minutes per year setting
  src/timer/timer_game_calendar.cpp
Labels: backport requested, preview

#12181 Fix #12176: Ships are circling in one place
  src/pathfinder/yapf/yapf_ship.cpp
Labels: backport requested

#12221 Remove: [Script] random_deviation from setting description table
  src/ai/ai.hpp
  src/ai/ai_core.cpp
  src/game/game.hpp
  src/game/game_core.cpp
  src/game/game_gui.cpp
  src/lang/english.txt
  src/saveload/afterload.cpp
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_info_docs.hpp
  src/script/script_config.cpp
  src/script/script_config.hpp
  src/script/script_gui.cpp
  src/script/script_info.cpp
Labels: backport requested

#12226 Fix #12225, 977aba7: [Script] Missing AI:ResetConfig support for running AI config
  src/ai/ai_core.cpp
Labels: backport requested

#12108 Add: Portuguese Escudo currency
  src/currency.cpp
  src/currency.h
  src/lang/english.txt
  src/table/settings/locale_settings.ini
Labels: preview

#12139 Fix #12134: Use correct error messages if clearing drive-through road stops fails
  src/station_cmd.cpp
Labels: backport requested, preview

#12220 Fix #12203: When unbunching at a depot, don't overlook implicit orders
  src/vehicle.cpp
Labels: backport requested

#12205 Change: [Script] Match FormatString behaviour more closely
  src/script/api/script_text.cpp
  src/script/api/script_text.hpp
Labels: backport requested

#12243 Codechange: [CI] use "cargo install --locked" to use pinned dependency versions
  .github/workflows/release-linux.yml
  .github/workflows/release-macos.yml
  .github/workflows/release-windows.yml
  docs/symbol_server.md
Labels: backport requested

#12136 Fix #12118: When adding an unbunching order, properly check for unsafe conditions
  src/order_cmd.cpp
  src/order_gui.cpp
  src/vehicle.cpp
  src/vehicle_base.h
Labels: backport requested

#12241 Codechange: [CI] manually install vcpkg for all targets
  .github/workflows/ci-build.yml
  .github/workflows/release-macos.yml
  .github/workflows/release-windows.yml
Labels: backport requested

#12237 Codechange: [CI] switch MacOS to the macos-14 runner
  .github/workflows/ci-build.yml
  .github/workflows/release-macos.yml
Labels: backport requested

#12244 Revert #11606: Don't auto-build past tunnelbridge ends
  src/rail_cmd.cpp
  src/road_cmd.cpp
Labels: backport requested

#12245 Fix ab315d0: Don't show "insert order" errors in the console
  src/order_gui.cpp
Labels: backport requested

#12242 Codechange: [CI] switch to arm64 for MacOS builds
  .github/workflows/ci-build.yml
Labels: backport requested

#12262 Fix #12255: inconsistent punctuation in English
  src/lang/english.txt
Labels: backport requested

#12271 Codefix: [CI] Store vcpkg outside the repository folder
  .github/workflows/ci-linux.yml
  .github/workflows/ci-macos.yml
  .github/workflows/ci-windows.yml
  .github/workflows/codeql.yml
  .github/workflows/release-macos.yml
  .github/workflows/release-windows.yml
Labels: backport requested

#12276 Change: Update OpenTTD TTF fonts to v0.6
  media/baseset/OpenTTD-Mono.ttf
  media/baseset/OpenTTD-Sans.ttf
  media/baseset/OpenTTD-Serif.ttf
  media/baseset/OpenTTD-Small.ttf
  media/baseset/OpenTTD-font.md
Labels: backport requested

#12286 Fix #12279: Update random path each step
  src/pathfinder/yapf/yapf_ship.cpp
Labels: backport requested

#12163 Add: Basic autocompletion on tab for console commands
  src/CMakeLists.txt
  src/autocompletion.cpp
  src/autocompletion.h
  src/console_gui.cpp
  src/network/network_chat_gui.cpp
  src/string.cpp
  src/string_func.h
  src/tests/string_func.cpp
  src/video/cocoa/cocoa_wnd.mm
Labels: preview

#12285 Fix #12280: Allow ships 90 degree turns if only choice
  src/pathfinder/yapf/yapf_ship.cpp
Labels: backport requested

#12304 Add: track savegame size to report with survey
  src/crashlog.cpp
  src/gfx.cpp
  src/misc.cpp
  src/network/core/config.h
  src/network/network_client.cpp
  src/network/network_survey.cpp
  src/openttd.cpp
  src/openttd.h
  src/saveload/misc_sl.cpp
  src/saveload/saveload.cpp
  src/survey.cpp
  src/survey.h
Labels: backport requested

#12274 Codefix f1e999ec: use RandomRange(l) instead of _random.Next(l)
  src/pathfinder/yapf/yapf_ship.cpp
Labels: backport requested

#12310 Codefix: allow preview label on PRs against release branches too
  .github/workflows/preview.yml
Labels: backport requested

#12321 Fix #12316, 268e512: Support for enum storage type in GenerateWidget.cmake
  cmake/scripts/GenerateWidget.cmake
Labels: backport requested

#12322 Fix #12319, 3a676a5: Some SSE blitters were broken due to ODR violations
  src/blitter/32bpp_sse_func.hpp
  src/blitter/32bpp_sse_type.h
Labels: backport requested, backport squash

#12325 Fix #12302: Allow empty train engines to use an invalid cargo type.
  src/newgrf.cpp
Labels: backport requested

#12292 Codechange: [CI] Use Azure Code Signing for Windows build
  .github/workflows/release-windows.yml
  cmake/InstallAndPackage.cmake
  os/windows/sign.bat
  os/windows/sign_azure.ps1
Labels: backport requested

#12313 Fix #12305: Crash with large positive sprite x offset in engine preview window
  src/engine_gui.cpp
Labels: backport requested

#12278 Codechange: Reduce size of class WaterRegion
  src/pathfinder/water_regions.cpp
Labels: backport requested

#12352 Codefix: Incorrect pluralisation in last service/service interval texts
  src/lang/english.txt
Labels: backport requested

#12348 Fix #12347: Crash attempting to find catchment tiles of a station with no catchment area.
  src/script/api/script_tilelist.cpp
Labels: backport requested

#12359 Fix #12092: Incorrect x-axis in cargo payment graph window
  src/graph_gui.cpp
Labels: backport requested

#12353 Fix: crash to desktop when attempting to join a company while not joined (yet)
  src/console_cmds.cpp
  src/network/network.cpp
Labels: backport requested

#12364 Fix: Don't let CT_INVALID map to valid cargo type.
  src/cargotype.cpp
Labels: backport requested

#12284 Change: Add dividers in vehicle group action dropdown
  src/vehicle_gui.cpp
Labels: preview

#12367 Fix 2fd9096: Label for fruit incorrectly changed to `FRUI` from `FRUT`.
  src/cargo_type.h
Labels: backport requested

#12370 Fix #12368: Incorrect offset for click position within industry chain window.
  src/industry_gui.cpp
Labels: backport requested

#12375 Fix #12268: Capitalize "Wait to unbunch" order string
  src/lang/english.txt
Labels: backport requested

#12377 Fix: do not send chat to clients that have not authorized yet
  src/network/network_server.cpp
Labels: backport requested

#12389 Fix #12388: Vehicle::CopyVehicleConfigAndStatistics not releasing unit number
  src/train_cmd.cpp
  src/vehicle.cpp
  src/vehicle_base.h
Labels: backport requested

#12390 Change: [CI] Always use latest stable Xcode
  .github/workflows/ci-macos.yml
  .github/workflows/release-macos.yml
Labels: backport requested

#12369 Fix #12387, eabb9db: [NewGRF] Wrong tile offset passed to rail station CB 149 (slope check)
  src/station_cmd.cpp
Labels: component: NewGRF, backport requested

#12372 Fix: [Script] ScriptSubsidy::GetExpireDate should return an economy-date
  src/script/api/script_subsidy.cpp
Labels: backport requested

#12397 Fix: "-q" displays NewGRF IDs in the wrong byte-order
  src/openttd.cpp
Labels: backport requested

#12398 Cleanup 69d5b9d3: actually clean up all remnants of "no-thread" builds
  COMPILING.md
  cmake/Options.cmake
Labels: backport requested
