Repository OpenTTD/OpenTTD, pull requests merged in 2024-01, with the labels that each got.

#11683 Change: Reorganize Settings menu items
  src/lang/english.txt
  src/settings_gui.cpp
Labels: preview

#10543 Feature: Region-based pathfinder for ships (buoys no longer required!)
  src/genworld.cpp
  src/pathfinder/CMakeLists.txt
  src/pathfinder/water_regions.cpp
  src/pathfinder/water_regions.h
  src/pathfinder/yapf/CMakeLists.txt
  src/pathfinder/yapf/yapf_ship.cpp
  src/pathfinder/yapf/yapf_ship_regions.cpp
  src/pathfinder/yapf/yapf_ship_regions.h
  src/saveload/CMakeLists.txt
  src/saveload/afterload.cpp
  src/saveload/saveload.cpp
  src/saveload/saveload.h
  src/saveload/water_regions_sl.cpp
  src/track_func.h
  src/track_type.h
  src/tunnelbridge_cmd.cpp
  src/water_cmd.cpp
  src/waypoint_cmd.cpp
Labels: preview

#11790 Fix #11714: [SDL] remove hint to avoid hardware acceleration
  src/video/sdl2_v.cpp
Labels: preview

#11750 Change: simplified water region evaluation, removed savegame data
  src/genworld.cpp
  src/landscape.cpp
  src/map.cpp
  src/object_cmd.cpp
  src/pathfinder/water_regions.cpp
  src/pathfinder/water_regions.h
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/saveload/water_regions_sl.cpp
  src/tunnelbridge_cmd.cpp
  src/water_cmd.cpp
  src/waypoint_cmd.cpp
Labels: preview

#11341 Feature: Use real-time "wallclock" timekeeping units
  src/cheat_gui.cpp
  src/company_gui.cpp
  src/graph_gui.cpp
  src/lang/english.txt
  src/misc.cpp
  src/order_cmd.cpp
  src/order_func.h
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/settings_gui.cpp
  src/settings_table.cpp
  src/settings_type.h
  src/strgen/strgen_base.cpp
  src/strings.cpp
  src/subsidy_gui.cpp
  src/table/control_codes.h
  src/table/settings/company_settings.ini
  src/table/settings/economy_settings.ini
  src/table/settings/gui_settings.ini
  src/table/strgen_tables.h
  src/timer/timer_game_calendar.cpp
  src/timer/timer_game_calendar.h
  src/timer/timer_game_common.cpp
  src/timer/timer_game_common.h
  src/timer/timer_game_economy.cpp
  src/timer/timer_game_economy.h
  src/timetable_gui.cpp
  src/vehicle.cpp
  src/vehicle_gui.cpp
  src/widgets/graph_widget.h
Labels: preview

#11860 Change: set smooth-scrolling on by default
  src/table/settings/gui_settings.ini
Labels: preview

#11142 Feature: Setting to automatically restart server based on hours played
  src/network/network_server.cpp
  src/network/network_server.h
  src/openttd.cpp
  src/settings_type.h
  src/table/settings/network_settings.ini
Labels: candidate: yes

#11874 Change: rebrand Cheats as Sandbox Options
  src/cheat_gui.cpp
  src/lang/english.txt
  src/toolbar_gui.cpp
Labels: preview

#10734 Feature: [NewGRF] Allow higher max speeds for ships
  src/engine.cpp
  src/engine_type.h
  src/newgrf.cpp
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/ship_cmd.cpp
  src/table/engines.h
Labels: needs review: NewGRF

#11923 Change: position error window closer to cursor on large screens
  src/error_gui.cpp
Labels: preview

#9637 Change: Build signals to the next junction when dragging regardless of the Ctrl state
  src/lang/english.txt
  src/rail_cmd.cpp
  src/rail_gui.cpp
Labels: candidate: needs considering

#11224 Add: [GS] Allow to set max loan for each company separately
  src/command_type.h
  src/company_base.h
  src/company_cmd.cpp
  src/company_gui.cpp
  src/economy.cpp
  src/economy_type.h
  src/misc_cmd.cpp
  src/misc_cmd.h
  src/saveload/afterload.cpp
  src/saveload/company_sl.cpp
  src/saveload/saveload.h
  src/script/api/game_changelog.hpp
  src/script/api/script_company.cpp
  src/script/api/script_company.hpp
  src/table/settings/difficulty_settings.ini
Labels: needs review: Script API

#10606 Feature: Setting to scale cargo production of towns and industries
  src/economy_func.h
  src/economy_type.h
  src/industry_cmd.cpp
  src/industry_gui.cpp
  src/lang/english.txt
  src/object_cmd.cpp
  src/settings_gui.cpp
  src/settings_type.h
  src/table/settings/economy_settings.ini
  src/town_cmd.cpp
Labels: preview, candidate: needs considering, needs review: NewGRF
