Repository OpenTTD/OpenTTD, pull requests merged in 2024-02, with the labels that each got.

#11798 Fix #10118: Cycle through current signal group, not just path signals
  src/lang/english.txt
  src/rail_gui.cpp
  src/rail_gui.h
  src/table/settings/gui_settings.ini
Labels: preview

#11606 Fix #11528: Don't auto-build past tunnelbridge ends
  src/rail_cmd.cpp
  src/road_cmd.cpp
Labels: preview

#11945 Feature: Order flag to unbunch vehicles at depot
  src/aircraft_cmd.cpp
  src/base_consist.cpp
  src/base_consist.h
  src/lang/english.txt
  src/order_base.h
  src/order_cmd.cpp
  src/order_gui.cpp
  src/order_type.h
  src/roadveh_cmd.cpp
  src/saveload/afterload.cpp
  src/saveload/saveload.h
  src/saveload/vehicle_sl.cpp
  src/ship_cmd.cpp
  src/timetable_cmd.cpp
  src/train_cmd.cpp
  src/vehicle.cpp
  src/vehicle_base.h
  src/vehicle_cmd.cpp
  src/vehicle_gui.cpp
  src/widgets/order_widget.h
Labels: preview

#11947 Feature: NewGRF town production effect and multiplier
  src/cargotype.h
  src/newgrf.cpp
  src/table/cargo_const.h
  src/town_cmd.cpp
Labels: needs review: NewGRF

#11140 Fix #10983: [AdminPort] Correct order of messages
  src/company_cmd.cpp
  src/network/network_admin.cpp
  src/network/network_admin.h
  src/network/network_server.cpp
Labels: work: minor details

#12135 Fix: [Script] Only show debug script window at the end of savegame loading
  src/ai/ai_instance.cpp
  src/game/game_instance.cpp
Labels: backport requested

#12138 Fix #12133: [Script] Don't crash when emergency saving
  src/ai/ai_core.cpp
Labels: backport requested

#12126 Fix cb588d8d: Ordering of command per tick limit and pause mode filtering
  src/network/network_command.cpp
Labels: backport requested

#12141 Fix #12119: Remove red warning text when maximum loan is zero
  src/lang/english.txt
Labels: backport requested

#12143 Fix: Off by one in TimerGameEconomy::ConvertDateToYMD in wallclock mode
  src/timer/timer_game_economy.cpp
Labels: backport requested

#12146 Fix #12145: Incorrect date handling in date cheat in wallclock time-keeping mode
  src/cheat_gui.cpp
Labels: backport requested

#12150 Fix #12148, fca8166: Do not draw decimals when number of digits is 0
  src/strings.cpp
Labels: backport requested

#12132 Fix #12127, 555a379: Truncation ellipses rendered shadows even for black font without shadows
  src/gfx.cpp
Labels: backport requested

#12161 Fix #10490: Allow ships to exit depots if another is not moving at the exit point
  src/ship_cmd.cpp
Labels: preview

#12172 Fix fd9e72a: Helptext for timekeeping unit setting erroneously refers to vehicle movement
  src/lang/english.txt
Labels: backport requested

#12174 Fix d3c673e: Don't defer OnResize() after ReInit()
  src/window.cpp
  src/window_func.h
Labels: backport requested

#12165 Codechange: Use bitmap for free unit ID generation.
  src/company_base.h
  src/economy.cpp
  src/saveload/vehicle_sl.cpp
  src/train_cmd.cpp
  src/vehicle.cpp
  src/vehicle_base.h
  src/vehicle_cmd.cpp
Labels: backport requested

#12184 Fix: initialize _switch_mode_time so crash-logs before first game have a realistic time
  src/openttd.cpp
Labels: backport requested

#12187 Fix bf4b6696: [Script] Broken ScriptText circular reference detection
  src/script/api/script_text.cpp
  src/script/api/script_text.hpp
Labels: backport requested

#12188 Fix f6dd505: Missing savegame conversion for current_order
  src/saveload/afterload.cpp
Labels: backport requested
