Repository OpenTTD/OpenTTD, pull requests merged in 2024-07, with the labels that each got.

#12615 Codechange: Reduced size of water region by not storing tile area
  src/pathfinder/water_regions.cpp
Labels: work: needs rebase

#12830 Codechange: Slightly simplify code in clear_cmd.cpp.
  src/clear_cmd.cpp
Labels: preview

#12842 Fix #12840, ff3be45: "Show industry names" blank panel not initialized properly
  src/smallmap_gui.cpp
Labels: preview

#12861 Add: [Script] Include number of victims in ScriptEventVehicleCrashed
  src/aircraft_cmd.cpp
  src/disaster_vehicle.cpp
  src/roadveh_cmd.cpp
  src/script/api/ai_changelog.hpp
  src/script/api/game_changelog.hpp
  src/script/api/script_event_types.hpp
  src/train_cmd.cpp
  src/water_cmd.cpp
Labels: needs review: Script API

#12857 Change: Path signals now show green on junction-less tracks by default
  src/pathfinder/yapf/yapf_rail.cpp
  src/signal.cpp
  src/train_cmd.cpp
Labels: preview
