Repository OpenTTD/OpenTTD, pull requests merged in 2024-06, with the labels that each got.

#12765 Fix #12764: Crash when opening Detailed performance rating window with no companies.
  src/graph_gui.cpp
Labels: backport requested

#12650 Fix #12648: Ensure all uses of std::filesystem::path use native encoding.
  src/fileio.cpp
  src/game/game_text.cpp
  src/openttd.cpp
  src/signature.cpp
  src/strings.cpp
  src/survey.cpp
Labels: backport requested

#12776 Fix #10239: Use elevated snow height for roads on flat foundations
  src/road_cmd.cpp
Labels: backport requested, preview

#12673 Fix: ensure revision mismatch also considers random debugging status
  src/network/core/network_game_info.cpp
Labels: backport requested

#12763 Change: Allow bribing local authority when other company has exclusive rights
  src/town_cmd.cpp
Labels: preview

#12770 Add: Toggle for showing industry names in small map
  src/lang/english.txt
  src/smallmap_gui.cpp
  src/widgets/smallmap_widget.h
Labels: preview

#12822 Fix d8771b3: Scenario Editor construction state gone wrong
  src/town_cmd.cpp
Labels: preview

#12808 Change: Changing zoom no longer stops following vehicle
  src/main_gui.cpp
  src/vehicle_gui.cpp
  src/viewport_func.h
  src/window.cpp
Labels: preview
