Repository OpenTTD/OpenTTD, pull requests merged in 2024-05, with the labels that each got.

#12603 Doc: README.md: add Apache 2.0 licensing info for CheckAtomic.cmake
  CMakeLists.txt
  README.md
  cmake/3rdparty/llvm/CheckAtomic.cmake
  cmake/3rdparty/llvm/LICENSE.txt
Labels: backport requested, backport squash

#12613 Fix 2955ff3: CMake atomic check fails due to chosen compiler
  cmake/3rdparty/llvm/CheckAtomic.cmake
Labels: backport requested

#12642 Fix: Console command scrolling did not take account of padding and cursor width.
  src/console_gui.cpp
Labels: backport requested

#12660 Fix #12655, 4f6d75f: inconsistent state in client list and potential crash asfter client leaves
  src/network/network_server.cpp
Labels: backport requested

#12676 Fix #12594: Give descriptive error when company takeover fails due to vehicle limit
  src/company_cmd.cpp
  src/company_func.h
  src/economy.cpp
Labels: backport requested

#12679 Fix #12550: files were not saved in the right location when binary and configuration are in the same folder
  src/fileio.cpp
Labels: preview

#12680 Fix #12418, 338def1b06: Filename extension taken from wrong string.
  src/openttd.cpp
Labels: backport requested

#12684 Fix: Unable to choose a font name containing a hyphen.
  src/os/unix/font_unix.cpp
Labels: backport requested

#12689 Codefix: Compile warning with newer C++ compiler on MinGW.
  src/base_station_base.h
  src/vehicle_base.h
Labels: backport requested

#12686 Fix #12685: nullptr dereference when checking for equal loaded/loading groups.
  src/newgrf.cpp
Labels: backport requested

#12704 Fix: Make progress bars obey language direction.
  src/genworld_gui.cpp
  src/network/network_content_gui.cpp
  src/network/network_gui.cpp
  src/newgrf_gui.cpp
Labels: backport requested

#12705 Fix: Crash if interface scale or font size changes with chat box present.
  src/window.cpp
Labels: backport requested

#12678 Fix #12591: Give descriptive error when station construction fails due to wrong layout
  src/lang/english.txt
  src/station_cmd.cpp
Labels: backport requested

#12658 Fix #12563: Race condition setting finish flag in WinHTTP
  src/network/core/http_winhttp.cpp
Labels: backport requested

#12697 Fix: Social plugins not working on macOS
  cmake/PackageBundle.cmake
  os/macosx/openttd.entitlements
Labels: backport requested

#12662 Fix: Memory leak in CoreTextFontCache.
  src/os/macosx/font_osx.cpp
Labels: OS: MacOS

#12711 Fix: Reverse left/right keypress when editing RTL text.
  src/textbuf.cpp
  src/textbuf_type.h
Labels: backport requested

#12710 Fix d6ccfdb: GetCharPosition failed for RTL text.
  src/gfx_layout.cpp
Labels: backport requested

#12727 Fix #12283: Vehicle group dropdown shouldn't have default action
  src/group_gui.cpp
Labels: backport requested

#12729 Fix: Water infrastructure total when changing owner of object on water
  src/object_cmd.cpp
Labels: backport requested

#12726 Fix #12492: Clarify helptext for "minutes per year" setting
  src/lang/english.txt
Labels: backport requested
