Repository OpenTTD/OpenTTD, pull requests merged in 2025-01, with the labels that each got.

#13207 Add: Ability to toggle visibility of station signs by facility.
  src/dropdown.cpp
  src/dropdown_common_type.h
  src/dropdown_func.h
  src/lang/english.txt
  src/table/settings/misc_settings.ini
  src/toolbar_gui.cpp
  src/transparency.h
  src/transparency_gui.cpp
  src/viewport.cpp
Labels: preview

#12989 Fix #12968, d20df82: Added back ability to create unremovable houses
  src/town_cmd.cpp
Labels: work: minor details

#12877 Add: Ukrainian Hryvnia currency
  src/currency.cpp
  src/currency.h
  src/lang/english.txt
  src/table/settings/locale_settings.ini
Labels: candidate: needs considering
